<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeManagement.Application.Contracts\CodeManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\PersonManagement.Application.Contract\PersonManagement.Application.Contract.csproj" />
    <ProjectReference Include="..\PersonManagement.Domain\PersonManagement.Domain.csproj" />
  </ItemGroup>

</Project>
